### ISSUE TITLE
At correction for partial quantity tab, refund amount to seller minus seller defined shipping fee

### ISSUE THREAD

**Issue by Linhpelo** [phuongmnguyen/dntt_calculator#5]
Hi Phương,

Please check order 36559559347410, the seller's revenue exclude seller defined shipping fee, shipping fee is sponsored by Shopee, not by seller. In the formula for calculating the refund to the seller, it deducted seller defined shipping fee so the amount is not correct

**Comment by phuongmnguyen** [comment]
Data source has an issue:
![image](https://user-images.githubusercontent.com/62538612/78522024-8a112780-77fe-11ea-8c8f-fa3be976b632.png)
Both seller & shopee shipping discounts are 15,100 VND. Raised JIRA ticket for Reg dev to check

**Comment by phuongmnguyen** [comment]
We should be using final_seller_paid_shipping_fee from the shipping data objectobject
![image](https://user-images.githubusercontent.com/62538612/78643039-3a0d9000-78e6-11ea-8414-78ce132e617c.png)
Changes implemented in commit https://github.com/phuongmnguyen/dntt_calculator/commit/6d943e6ef00a8073b422281ef9fa2897fd3ca751
